type User @entity {
  # wallet address
  id: ID!
  # vesting schedules
  vestingSchedules: [VestingSchedule!]! @derivedFrom(field: "beneficiary")
  # claims
  claims: [Claim!] @derivedFrom(field: "beneficiary")
  #  sum of all vesting schedule amounts
  totalAllocation: BigInt!
  #  sum of all upfront releases and token claim amounts
  totalReleased: BigInt!
}

type VestingSchedule @entity {
  # vesting schedule Id
  id: ID!
  beneficiary: User!
  cliff: Int!
  start: Int!
  duration: Int!
  slicePeriodSeconds: Int!
  revocable: Boolean!
  amountTotal: BigInt!
  released: BigInt!
  revoked: Boolean!
  upFront: BigInt!
}

enum ClaimType {
  UpFront
  PostVesting
}

type Claim @entity {
  id: ID!
  amount: BigInt!
  vestingSchedule: VestingSchedule!
  beneficiary: User!
  claimType: ClaimType!,
  timestamp: Int!
}
